name: Build and Compile

on:
  push:
    branches:
      - main
      - dev
      - feature*
      - master
  pull_request:
    branches:
      - main
      - dev
      - feature*
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        ./config.sh

    - name: Build and Compile
      run: |
        cd src
        ./build.py -c -ninja ws63-liteos-app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: standard-bs21e-1100e
        path: src/output/ws63/fwpkg